### ISSUE TITLE
Add husky, semantic release and GH action for healthcheck (runs lint and test script on every PR to main)

### ISSUE THREAD

**Issue by npranto** [npranto/ecommercer#6]
### Description:
Add **Husky**, **Semantic Release**, and a **GitHub Action** to automate code quality checks and releases. This ensures:
- Pre-commit hooks for linting and testing.
- Automated versioning and changelog generation using Semantic Release.
- Health checks (linting and testing) on every PR to the `main` branch.

---

### Acceptance Criteria:
- Husky pre-commit hooks for running `lint` and `test` scripts.
- Semantic Release configured for automated versioning and changelog generation.
- GitHub Action to run `lint` and `test` scripts on every PR to `main`.
- All configurations documented and working.

---

#### 1. **Install Husky and Set Up Pre-Commit Hooks**
   - Install Husky:
     ```bash
     npm install husky lint-staged --save-dev
     ```
   - Initialize Husky:
     ```bash
     npx husky init
     ```
   - Add a pre-commit hook to run `lint` and `test` scripts:
     ```bash
     echo "npx lint-staged" > .husky/pre-commit
     ```
   - Update package.json scripts and lint-staged props:
     ```bash
     "scripts": {
        "prepare": "husky"
     },
     ...
     "husky": {
        "hooks": {
         "pre-commit": "lint-staged"
        }
     },
     "lint-staged": {
       "src/**/*.{js,jsx,ts,tsx,json}": [
          "npm run format"
       ]
     }
     ```

---

#### 2. **Set Up Semantic Release**
   - Install Semantic Release and required plugins:
     ```bash
     npm install semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github --save-dev
     ```
   - Create a `.releaserc.json` file for Semantic Release configuration:
     ```json
     {
       "branches": ["main"],
       "plugins": [
         "@semantic-release/commit-analyzer",
         "@semantic-release/release-notes-generator",
         "@semantic-release/changelog",
         "@semantic-release/npm",
         "@semantic-release/git",
         "@semantic-release/github"
       ]
     }
     ```
   - Add a `release` script to `package.json`:
     ```json
     "scripts": {
       "release": "semantic-release"
     }
     ```

---

#### 3. **Set Up GitHub Action for Health Checks**
   - Create a `.github/workflows/healthcheck.yml` file:
     ```yaml
     name: Health Check
     on:
       pull_request:
         branches:
           - main
     jobs:
       lint-and-test:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v3

           - name: Set up Node.js
             uses: actions/setup-node@v3
             with:
               node-version: 18

           - name: Install dependencies
             run: npm install

           - name: Run Linting
             run: npm run lint

           - name: Run Tests
             run: npm run test
     ```

---

#### 4. **Update Documentation**
   - Add a section to the `README.md` file explaining:
     - How Husky ensures code quality before commits.
     - How Semantic Release automates versioning and changelog generation.
     - How the GitHub Action ensures health checks on every PR to `main`.

---

#### 5. **Test the Setup**
   - Test Husky:
     - Make a change and attempt to commit. The `lint` and `test` scripts should run automatically.
   - Test Semantic Release:
     - Merge a PR with a valid commit message (e.g., `feat: add new feature`) and verify that a new release is created.
   - Test GitHub Action:
     - Open a PR to `main` and verify that the health check workflow runs successfully.

---

### Notes:
- Ensure all team members have Husky installed by running `npm install` after pulling the latest changes.
- Commit messages must follow the [Conventional Commits](https://www.conventionalcommits.org/) format for Semantic Release to work correctly.
- The GitHub Action will fail if either the `lint` or `test` scripts fail, ensuring no broken code is merged into `main`.

---

### References:
- [Husky Documentation](https://typicode.github.io/husky/)
- [Semantic Release Documentation](https://semantic-release.gitbook.io/semantic-release/)
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
